### PR TITLE
BCON-377 - MPS-API - PUT operation BUG

### PR DESCRIPTION
**Pull request by vgolyachenko**
* updated deepmerge.util to replace arrays instead of concatenation

### CODE REVIEW

**Review by dominathan — CHANGES_REQUESTED** [review]
It looks good.  Could you add a test with an object that has both

{ meta: { prop: [] }, otherProp: [] } and show that it only concats the meta one?

**Comment by vgolyachenko** [comment]
> It looks good. Could you add a test with an object that has both
> 
> { meta: { prop: [] }, otherProp: [] } and show that it only concats the meta one?

@dominathan added

**Comment by vgolyachenko** [comment]
@dominathan please, pay attention that I leave logic to compare (and merge) arrays items with same url/system/id fields
but it's only for "meta" field
is this correct?

**Review by dominathan — APPROVED** [review]
I think that's correct for now.

In general, the server should control the meta values so I think doing it this way makes sense.  We probably don't want to delete things for tags.

The next part of this ticket is you'll need to bump the version of MPS-API and vendor_onboarding so we get these changes.

**Pull request merged**
